apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
        - name: task-manager
          image: 485067906330.dkr.ecr.us-east-1.amazonaws.com/task-manager:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: task-manager